### ISSUE TITLE
Inline (don't wrap) array of short values

### ISSUE THREAD

**Issue by rayshan** [rafeca/prettyjson#13]
Hi, thanks for the hard work on this awesome utility module.

To take advantage of horizontal instead of vertical screen space, can we have an option to change this:

```
installs:
  - 287
  - 239
  - 220
  - 186
  - 170
  - 247
  - 242
  - 280
  - 242
  - 275
  - 163
  - 183
  - 280
  - 335
```

To this:

```
installs: 287, 239, 220, 186, 170, 247, 242, 280, 242, 275, 163, 183, 280, 335
```

**Comment by rafeca** [comment]
Sorry for the delay, your suggestion was added in `1.1.0`: https://github.com/rafeca/prettyjson/releases/tag/1.1.0

Thanks for the suggestion!

**Comment by rayshan** [comment]
:tada:
