### ISSUE TITLE
Is there any way to keep the output format as json, but colorized?

### ISSUE THREAD

**Issue by apobbati** [rafeca/prettyjson#19]
Hi,

Is there any way to keep the output format as json, but colorized? I'd be happy to send a pull request if you can point me to the files to look at.

Thanks,

**Comment by rafeca** [comment]
I don't think that this package could be used for that, as the logic for printing in the current format is coupled with the logic for handling colors. You may look if there is already a package for that (or create your own from scratch :smiley:)
