### ISSUE TITLE
io.js compatibility

### ISSUE THREAD

**Issue by ronkorving** [rafeca/prettyjson#20]
You have an engines field that doesn't really let io.js in. Is that something that could be addressed? Something tells me this module is perfectly capable of being used in io.js...

Log:

```
npm WARN engine prettyjson@1.1.2: wanted: {"node":">= 0.10.0 < 0.13.0"} (current: {"node":"3.0.0","npm":"2.13.3"})
```

**Comment by rafeca** [comment]
Yes, this module didn't use any special feature of any nodejs version, so I've just removed the engines field completely from package.json. You can now install version `1.1.3`.

Thanks for the report!

**Comment by ronkorving** [comment]
Cool, thanks :)
