### ISSUE TITLE
Breaking Change 1.2.0

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [rafeca/prettyjson#30]
The latest release (1.2.0) breaks existing functionality. Previously (1.1.3) the render method handled functions gracefully. When a function is encountered in the latest release, it recursively iterates through properties, of which are `length`,`name`,`prototype`,`constructor`, and appears to infinitely recurse on the `constructor` property (which makes sense if it is indeed a function).

Example object to render:
```javascript
{
    key: "value",
    someAction: function(param) { return "obj." + param + ".value";}
}
```

**Comment by rafeca** [comment]
Sorry for the issue, it's been fixed in 65d9f9 and I've released v1.2.1 with the fix
