### ISSUE TITLE
Feature Request: Option for indenting everything with n spaces

### ISSUE THREAD

**Issue by basvdijk** [rafeca/prettyjson#42]
This feature is typically useful for debugging messages so
```
Receiving data:

key1:     12
key2:     23
key3:     12
```
becomes:

```
Receiving data:

    key1:     12
    key2:     23
    key3:     12
```

**Comment by gswalden** [comment]
This is currently possible:

<img width="506" alt="screen shot 2017-11-17 at 01 16 18" src="https://user-images.githubusercontent.com/3459542/32932042-1f11a93c-cb35-11e7-8ce8-9aca7cdcf815.png">

The argument `8` is specifying eight initial spaces.

**Comment by basvdijk** [comment]
Thanks!
