### ISSUE TITLE
Dependencie on colors package breaks code.

### ISSUE THREAD

**Issue by Screpuh** [rafeca/prettyjson#55]
Hi, please check https://github.com/Marak/colors.js/issues/289 for all details.

Looks like the color package is deliberately broken so all dependencies break on update. 

Would it be possible for now to update the package.json file to lock the colors package to the last stable version: 1.4.0

Kind regards

**Comment by rafeca** [comment]
I've released v1.2.2 which should fix the problem, thanks for the report!
